import smtplib
from email.message import EmailMessage
from datetime import datetime
from config.config_manager import get_setting

SENDER_EMAIL = "iotshieldproject@gmail.com"
APP_PASSWORD = "eytd qbzp bkll xqip"


def send_email_alert(subject, body):
    try:
        recipient_email = get_setting("recipient_email")

        if not recipient_email:
            print("[EMAIL ERROR] No recipient email configured.")
            return False

        msg = EmailMessage()
        msg["Subject"] = subject
        msg["From"] = SENDER_EMAIL
        msg["To"] = recipient_email
        msg.set_content(body)

        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as smtp:
            smtp.login(SENDER_EMAIL, APP_PASSWORD)
            smtp.send_message(msg)

        print("[EMAIL] Alert email sent successfully.")
        return True

    except Exception as e:
        print(f"[EMAIL ERROR] {e}")
        return False


def send_test_email():
    subject = "IoT-Shield Test Notification"

    body = f"""
This is a test email generated by IoT-Shield.

If you received this email, your notification settings are working correctly.

Generated at:
{datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
"""

    return send_email_alert(subject, body)